In [ ]:
import pandas as pd
import numpy as np

In [ ]:

import pandas as pd
import numpy as np

data = [
    {'Name': 'Alice', 'Age': 25, 'Gender': 'Female', 'Email': 'alice@example.com', 'Address': '123 Main St', 'Salary': 60000},
    {'Name': 'Bob', 'Age': 30, 'Gender': 'Male', 'Email': 'bob@example.com', 'Address': '456 Oak Ave', 'Salary': 75000},
    {'Name': 'Charlie', 'Age': 28, 'Gender': 'Male', 'Email': 'charlie@example.com', 'Address': '789 Pine Ln', 'Salary': 80000},
    {'Name': 'David', 'Age': 35, 'Gender': 'Male', 'Email': 'david@example.com', 'Address': '1011 Elm Rd', 'Salary': 90000},
    {'Name': 'Eve', 'Age': 22, 'Gender': 'Female', 'Email': 'eve@example.com', 'Address': '1213 Birch Blvd', 'Salary': 55000}
]

df = pd.DataFrame(data)

df

      Name  Age  Gender                Email          Address  Salary
0    Alice   25  Female    alice@example.com      123 Main St   60000
1      Bob   30    Male      bob@example.com      456 Oak Ave   75000
2  Charlie   28    Male  charlie@example.com      789 Pine Ln   80000
3    David   35    Male    david@example.com      1011 Elm Rd   90000
4      Eve   22  Female      eve@example.com  1213 Birch Blvd   55000

In [ ]:
df['New Col'] = df['Salary'] * .01
df

      Name  Age  Gender                Email          Address  Salary  New Col
0    Alice   25  Female    alice@example.com      123 Main St   60000    600.0
1      Bob   30    Male      bob@example.com      456 Oak Ave   75000    750.0
2  Charlie   28    Male  charlie@example.com      789 Pine Ln   80000    800.0
3    David   35    Male    david@example.com      1011 Elm Rd   90000    900.0
4      Eve   22  Female      eve@example.com  1213 Birch Blvd   55000    550.0

In [ ]:
df['username'] = df['Email'].str.split('@').str[0]
df

,Name,Age,Gender,Email,Address,Salary,New Col,username
0,Alice,25,Female,alice@example.com,123 Main St,60000,600.0,alice
1,Bob,30,Male,bob@example.com,456 Oak Ave,75000,750.0,bob
2,Charlie,28,Male,charlie@example.com,789 Pine Ln,80000,800.0,charlie
3,David,35,Male,david@example.com,1011 Elm Rd,90000,900.0,david
4,Eve,22,Female,eve@example.com,1213 Birch Blvd,55000,550.0,eve

In [ ]:
df.loc[4:6 , ['Name' , 'Salary' , 'Email']]

  Name  Salary            Email
4  Eve   55000  eve@example.com

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      object
 1   Age      5 non-null      int64
 2   Gender   5 non-null      object
 3   Email    5 non-null      object
 4   Address  5 non-null      object
 5   Salary   5 non-null      int64
 6   New Col  5 non-null      float64
dtypes: float64(1), int64(2), object(4)
memory usage: 412.0+ bytes

In [ ]:
df[['Age' , 'Salary']]

   Age  Salary
0   25   60000
1   30   75000
2   28   80000
3   35   90000
4   22   55000

In [ ]:
df[['Age' , 'Salary']] > 30

     Age  Salary
0  False    True
1  False    True
2  False    True
3   True    True
4  False    True

In [ ]:
df(['Age','Salary']>= 30)

TypeError: '>=' not supported between instances of 'list' and 'int'

KeyError: ('Age', 'Salary')

In [ ]:
df[df['Salary'] > 80000]

    Name  Age Gender              Email      Address  Salary  New Col
3  David   35   Male  david@example.com  1011 Elm Rd   90000    900.0

In [ ]:
df [ df['Salary'] <= 5000]

Empty DataFrame
Columns: [Name, Age, Gender, Email, Address, Salary, New Col]
Index: []

In [ ]:
df[df['Age'] == 30]

  Name  Age Gender            Email      Address  Salary  New Col
1  Bob   30   Male  bob@example.com  456 Oak Ave   75000    750.0

In [ ]:
df['Age'] >= 30

0    False
1     True
2    False
3     True
4    False
Name: Age, dtype: bool

In [ ]:
df [ (df['Gender'] == 'Male') & (df['Salary'] >5000) ]

      Name  Age Gender                Email      Address  Salary  New Col
1      Bob   30   Male      bob@example.com  456 Oak Ave   75000    750.0
2  Charlie   28   Male  charlie@example.com  789 Pine Ln   80000    800.0
3    David   35   Male    david@example.com  1011 Elm Rd   90000    900.0

In [ ]:
df[df['Salary'].between(75000,80000)]

      Name  Age Gender                Email      Address  Salary  New Col
1      Bob   30   Male      bob@example.com  456 Oak Ave   75000    750.0
2  Charlie   28   Male  charlie@example.com  789 Pine Ln   80000    800.0

In [ ]:
df [ (df['Gender'] == 'Male' ) & (df['Salary'] > 75000)]

      Name  Age Gender                Email      Address  Salary
2  Charlie   28   Male  charlie@example.com  789 Pine Ln   80000
3    David   35   Male    david@example.com  1011 Elm Rd   90000

In [ ]:
df [ (df['Age'] > 25) & (df['Salary'] > 20000) ]

   index     Name  Age Gender                Email      Address  Salary
1      1      Bob   30   Male      bob@example.com  456 Oak Ave   75000
2      2  Charlie   28   Male  charlie@example.com  789 Pine Ln   80000
3      3    David   35   Male    david@example.com  1011 Elm Rd   90000

In [ ]:
df [ (df['Age'] > 25) | (df['Salary'] >= 60000) ]

   index     Name  Age  Gender                Email      Address  Salary
0      0    Alice   25  Female    alice@example.com  123 Main St   60000
1      1      Bob   30    Male      bob@example.com  456 Oak Ave   75000
2      2  Charlie   28    Male  charlie@example.com  789 Pine Ln   80000
3      3    David   35    Male    david@example.com  1011 Elm Rd   90000

In [ ]:
df [ (df['Age'] < 25) & ((df['Salary'] > 70000) | (df['New Col'] > 800) )]

KeyError: 'New Col'

In [ ]:
 df[df['Age'].isin([35 , 30 , 25])]

    Name  Age  Gender              Email      Address  Salary  New Col
0  Alice   25  Female  alice@example.com  123 Main St   60000    600.0
1    Bob   30    Male    bob@example.com  456 Oak Ave   75000    750.0
3  David   35    Male  david@example.com  1011 Elm Rd   90000    900.0

In [ ]:
df[df['Salary'].between(75000 , 80000)]

      Name  Age Gender                Email      Address  Salary
1      Bob   30   Male      bob@example.com  456 Oak Ave   75000
2  Charlie   28   Male  charlie@example.com  789 Pine Ln   80000

In [ ]:
df[df['Age'].between(10,30)]

   index     Name  Age  Gender                Email          Address  Salary
0      0    Alice   25  Female    alice@example.com      123 Main St   60000
1      1      Bob   30    Male      bob@example.com      456 Oak Ave   75000
2      2  Charlie   28    Male  charlie@example.com      789 Pine Ln   80000
4      4      Eve   22  Female      eve@example.com  1213 Birch Blvd   55000

In [ ]:
df[df['Salary'].between(50000 , 60000)]

   index   Name  Age  Gender              Email          Address  Salary
0      0  Alice   25  Female  alice@example.com      123 Main St   60000
4      4    Eve   22  Female    eve@example.com  1213 Birch Blvd   55000

In [ ]:
df[df['Age'].isin([10 , 40])]

Empty DataFrame
Columns: [index, Name, Age, Gender, Email, Address, Salary]
Index: []

In [ ]:
# prompt: create me a data frame with data types columns for integrets and column for string and one for boolean and floats and dates

import pandas as pd
import numpy as np

# Create a dictionary with different data types
data = {
    'IntegerColumn': [1, 2, 3, 4, 5],
    'StringColumn': ['A', 'B', 'C', 'D', 'E'],
    'BooleanColumn': [True, False, True, False, True],
    'FloatColumn': [1.1, 2.2, 3.3, 4.4, 5.5],
    'DateColumn': pd.to_datetime(['2023-10-26', '2023-10-27', '2023-10-28', '2023-10-29', '2023-10-30'])
}

# Create a Pandas DataFrame from the dictionary
df3 = pd.DataFrame(data)

# Print the DataFrame
df3

   IntegerColumn StringColumn  BooleanColumn  FloatColumn DateColumn
0              1            A           True          1.1 2023-10-26
1              2            B          False          2.2 2023-10-27
2              3            C           True          3.3 2023-10-28
3              4            D          False          4.4 2023-10-29
4              5            E           True          5.5 2023-10-30

In [ ]:
df

   index     Name  Age  Gender                Email          Address  Salary
0      0    Alice   25  Female    alice@example.com      123 Main St   60000
1      1      Bob   30    Male      bob@example.com      456 Oak Ave   75000
2      2  Charlie   28    Male  charlie@example.com      789 Pine Ln   80000
3      3    David   35    Male    david@example.com      1011 Elm Rd   90000
4      4      Eve   22  Female      eve@example.com  1213 Birch Blvd   55000

In [ ]:
df3

   IntegerColumn StringColumn  BooleanColumn  FloatColumn DateColumn
0              1            A           True          1.1 2023-10-26
1              2            B          False          2.2 2023-10-27
2              3            C           True          3.3 2023-10-28
3              4            D          False          4.4 2023-10-29
4              5            E           True          5.5 2023-10-30

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   IntegerColumn  5 non-null      int64
 1   StringColumn   5 non-null      object
 2   BooleanColumn  5 non-null      bool
 3   FloatColumn    5 non-null      float64
 4   DateColumn     5 non-null      datetime64[ns]
dtypes: bool(1), datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 297.0+ bytes

In [ ]:
df

   index     Name  Age  Gender                Email          Address  Salary
0      0    Alice   25  Female    alice@example.com      123 Main St   60000
1      1      Bob   30    Male      bob@example.com      456 Oak Ave   75000
2      2  Charlie   28    Male  charlie@example.com      789 Pine Ln   80000
3      3    David   35    Male    david@example.com      1011 Elm Rd   90000
4      4      Eve   22  Female      eve@example.com  1213 Birch Blvd   55000

In [ ]:
df['Salary'] = df['Salary'].astype('float')
df

   index     Name  Age  Gender                Email          Address   Salary
0      0    Alice   25  Female    alice@example.com      123 Main St  60000.0
1      1      Bob   30    Male      bob@example.com      456 Oak Ave  75000.0
2      2  Charlie   28    Male  charlie@example.com      789 Pine Ln  80000.0
3      3    David   35    Male    david@example.com      1011 Elm Rd  90000.0
4      4      Eve   22  Female      eve@example.com  1213 Birch Blvd  55000.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   index    5 non-null      int64
 1   Name     5 non-null      object
 2   Age      5 non-null      int64
 3   Gender   5 non-null      object
 4   Email    5 non-null      object
 5   Address  5 non-null      object
 6   Salary   5 non-null      float64
dtypes: float64(1), int64(2), object(4)
memory usage: 412.0+ bytes

In [ ]:
df['Salary'] = df['Salary'].astype('int')
df

      Name  Age  Gender                Email          Address  Salary  New Col
0    Alice   25  Female    alice@example.com      123 Main St   60000    600.0
1      Bob   30    Male      bob@example.com      456 Oak Ave   75000    750.0
2  Charlie   28    Male  charlie@example.com      789 Pine Ln   80000    800.0
3    David   35    Male    david@example.com      1011 Elm Rd   90000    900.0
4      Eve   22  Female      eve@example.com  1213 Birch Blvd   55000    550.0

In [ ]:
df

   index     Name  Age  Gender                Email          Address  Salary
0      0    Alice   25  Female    alice@example.com      123 Main St   60000
1      1      Bob   30    Male      bob@example.com      456 Oak Ave   75000
2      2  Charlie   28    Male  charlie@example.com      789 Pine Ln   80000
3      3    David   35    Male    david@example.com      1011 Elm Rd   90000
4      4      Eve   22  Female      eve@example.com  1213 Birch Blvd   55000

In [ ]:
df.select_dtypes('number')

   index  Age  Salary
0      0   25   60000
1      1   30   75000
2      2   28   80000
3      3   35   90000
4      4   22   55000

In [ ]:
df.select_dtypes('object')

      Name  Gender                Email          Address
0    Alice  Female    alice@example.com      123 Main St
1      Bob    Male      bob@example.com      456 Oak Ave
2  Charlie    Male  charlie@example.com      789 Pine Ln
3    David    Male    david@example.com      1011 Elm Rd
4      Eve  Female      eve@example.com  1213 Birch Blvd

SETTING NEW INDEX

In [ ]:
df

   index     Name  Age  Gender                Email          Address  Salary
0      0    Alice   25  Female    alice@example.com      123 Main St   60000
1      1      Bob   30    Male      bob@example.com      456 Oak Ave   75000
2      2  Charlie   28    Male  charlie@example.com      789 Pine Ln   80000
3      3    David   35    Male    david@example.com      1011 Elm Rd   90000
4      4      Eve   22  Female      eve@example.com  1213 Birch Blvd   55000

In [ ]:
 df.set_index('Name' , inplace = True)

In [ ]:
df.reset_index()

      Name  index  Age  Gender                Email          Address  Salary
0    Alice      0   25  Female    alice@example.com      123 Main St   60000
1      Bob      1   30    Male      bob@example.com      456 Oak Ave   75000
2  Charlie      2   28    Male  charlie@example.com      789 Pine Ln   80000
3    David      3   35    Male    david@example.com      1011 Elm Rd   90000
4      Eve      4   22  Female      eve@example.com  1213 Birch Blvd   55000

In [ ]:
# prompt: create me a data frame with columns a b c d new and number between 0 and 50 random in each columns

import pandas as pd
import numpy as np

# Create a DataFrame with random numbers between 0 and 50
data = {
    'a': np.random.randint(0, 50, size=10),
    'b': np.random.randint(0, 50, size=10),
    'c': np.random.randint(0, 50, size=10),
    'd': np.random.randint(0, 50, size=10),
    'new': np.random.randint(0, 50, size=10)
}

df = pd.DataFrame(data)

df

    a   b   c   d  new
0   5   0  37  11   18
1  24  33  36  25   22
2  45  12   0   5    8
3  21  38   3  44   33
4  24  43  45   5   36
5  48  38   9  16    0
6  43   7  17  11    7
7  47   3  46  42    6
8   8  37  26  13    9
9  34  20  38  24   21

In [ ]:
df['a'] + df['b']

0     5
1    57
2    57
3    59
4    67
5    86
6    50
7    50
8    45
9    54
dtype: int64

In [ ]:
df['NewCol'] = df['a'] + df['b']
df

    a   b   c   d  new  NewCol
0   5   0  37  11   18       5
1  24  33  36  25   22      57
2  45  12   0   5    8      57
3  21  38   3  44   33      59
4  24  43  45   5   36      67
5  48  38   9  16    0      86
6  43   7  17  11    7      50
7  47   3  46  42    6      50
8   8  37  26  13    9      45
9  34  20  38  24   21      54

In [ ]:
df.to_csv('Python script.csv')
df

      Name  Age  Gender                Email          Address  Salary  New Col
0    Alice   25  Female    alice@example.com      123 Main St   60000    600.0
1      Bob   30    Male      bob@example.com      456 Oak Ave   75000    750.0
2  Charlie   28    Male  charlie@example.com      789 Pine Ln   80000    800.0
3    David   35    Male    david@example.com      1011 Elm Rd   90000    900.0
4      Eve   22  Female      eve@example.com  1213 Birch Blvd   55000    550.0

In [ ]:
import files
from files download.