In [ ]:
 import pandas as pd
import numpy as np

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
list =[1,2,3,4,5,9,8]
print(list,)

[1, 2, 3, 4, 5, 9, 8]

In [ ]:
for items in list:
    print(items)

1
2
3
4
5
9
8

In [ ]:
name ='esraa'
age = 25
txt = f'{name} is {age} old '
print(txt)

esraa is 25 old

In [ ]:
tx2 = 'name is {} and age {}'.format(name,age)
print(tx2)

name is esraa and age 25

In [ ]:
fa = f' hello aevary one  my age {25*66}'
print(fa)

 hello aevary one  my age 1650

In [ ]:
list2 =['esraa' ,'ahmed' ,'nore']
list2.sort()
print(list2)
list2.append("mohmed")
print(list2)
list2.insert(1,'ali')
print(list2)
list2.count('nore')
print(list2)
list3 =['esraa' ,'ahmed' ,'nore']
list2.extend(list3)
print(list2)
list3.reverse()
print(list3)
mylist=list2.copy()
print(mylist)

['ahmed', 'esraa', 'nore']
['ahmed', 'esraa', 'nore', 'mohmed']
['ahmed', 'ali', 'esraa', 'nore', 'mohmed']
['ahmed', 'ali', 'esraa', 'nore', 'mohmed']
['ahmed', 'ali', 'esraa', 'nore', 'mohmed', 'esraa', 'ahmed', 'nore']
['nore', 'ahmed', 'esraa']
['ahmed', 'ali', 'esraa', 'nore', 'mohmed', 'esraa', 'ahmed', 'nore']

In [ ]:
tuple = ('esraa','norr','ahmed')
print(tuple)
print(len(tuple))
print(type(tuple))
tuple2=(1,2,3,4,5)
print(tuple2)
print(tuple2[1:3])
tuple3 = tuple + tuple2
print(tuple3)

('esraa', 'norr', 'ahmed')
3
<class 'tuple'>
(1, 2, 3, 4, 5)
(2, 3)
('esraa', 'norr', 'ahmed', 1, 2, 3, 4, 5)

In [ ]:
set ={'car','bmw','kay' }
print(set)
set.add('audi')
print(set)
set.remove('bmw')
print(set)

{'car', 'kay', 'bmw'}
{'car', 'kay', 'bmw', 'audi'}
{'car', 'kay', 'audi'}

In [ ]:
set1 = {"a", "b", "c"}
set2 = {1, 2, 3}

set3 = set1.union(set2)
print(set3)

{1, 2, 'a', 3, 'b', 'c'}

In [ ]:
thisset = {"apple", "banana", "cherry"}

thisset.remove("banana")

print(thisset)

{'cherry', 'apple'}

In [ ]:
thisset = {"apple", "banana", "cherry"}
print(dir(1))

['__abs__', '__add__', '__and__', '__bool__', '__ceil__', '__class__', '__delattr__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floor__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__le__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rrshift__', '__rshift__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__trunc__', '__xor__', 'as_integer_ratio', 'bit_count', 'bit_length', 'conjugate', 'denominator', 'from_bytes', 'imag', 'numerator', 'real', 'to_bytes']

direct

In [ ]:
direc = {
    'name':'esraa',
    'age' : 20 ,
    'city':'cairo',
    'country':'egypt'

}
print(direc)
print(type(direc))
print(len(direc))

{'name': 'esraa', 'age': 20, 'city': 'cairo', 'country': 'egypt'}
<class 'dict'>
4

In [ ]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
x = thisdict["model"]
print(x)
thisdict["color"] ="red"
print(thisdict)
thisdict.update({"year": 2020})
print(thisdict)

Mustang
{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'red'}
{'brand': 'Ford', 'model': 'Mustang', 'year': 2020, 'color': 'red'}

In [ ]:
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}

x = car.items()

print(x) #before the change

car["year"] = 2020

print(x) #after the change

dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 1964)])
dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 2020)])

In [ ]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict.pop("model")
print(thisdict)
thisdict.pop("brand")
print(thisdict)

{'brand': 'Ford', 'year': 1964}
{'year': 1964}

In [ ]:
myfamily = {
  "child1" : {
    "name" : "Emil",
    "year" : 2004
  },
  "child2" : {
    "name" : "Tobias",
    "year" : 2007
  },
  "child3" : {
    "name" : "Linus",
    "year" : 2011
  }
}

print(myfamily["child2"]["name"])
print(myfamily)

Tobias
{'child1': {'name': 'Emil', 'year': 2004}, 'child2': {'name': 'Tobias', 'year': 2007}, 'child3': {'name': 'Linus', 'year': 2011}}

ifffffff and elseeeeeeee

In [ ]:
a=23
b=100
if a < b :
  print("t")

t

In [ ]:
day = 4
match day:
  case 1 | 2 | 3 | 4 | 5:
    print("Today is a weekday")
  case 6 | 7:
    print("I love weekends!")

Today is a weekday

In [ ]:
day = 4

match day:
    case 1:
        print("Monday")
    case 2:
        print("Tuesday")
    case 3:
        print("Wednesday")
    case 4:
        print("Thursday")
    case _:
        print("Not a valid day")

Thursday

In [ ]:
day =2
match day :
    case 1:
      print('monday')
    case 2:
      print('tuesday')
    case 3:
      print('wednesday')
    case 4:
      print('thursday')
    case 5:
      print('friday')

tuesday

In [ ]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)

apple
banana
cherry

In [ ]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
    if x == "banana":
        break
    print(x)

apple

In [ ]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  if x == "banana":
    continue # هيتخطى السطر اللي بعده ويرجع لللوب
  print(x)

apple
cherry

python function

In [ ]:
def skills (**skill):
  print(skill)
  skills(lang ='python',tool='sql',soft='teamwork')

In [ ]:
def skills(**skill):
    for key, value in skill.items():
        print(f"{key} → {value}")

skills(lang='Python', tool='SQL', soft='Teamwork')

In [ ]:
def skills(**skill):
    for key , value in skill.items():
      print(f'{key}:{value}')
skills(lang='python',tool='sql',soft='teamwork')

lang:python
tool:sql
soft:teamwork

NameError: name 'k' is not defined

ما هي مكتبة NumPy؟

NumPy اختصار لـ: Numerical Python.

مكتبة في بايثون متخصصة في:

التعامل مع المصفوفات Arrays (أسرع من القوائم list).

إجراء عمليات رياضية وإحصائية متقدمة.

الأساس لمعظم مكتبات الذكاء الاصطناعي وتحليل البيانات (مثل Pandas, Scikit-learn, TensorFlow).

In [1]:
import numpy as np

# مصفوفة 1D
arr1 = np.array([1, 2, 3, 4])
print(arr1)

# مصفوفة 2D
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]

🟢 دوال إنشاء سريعة

In [ ]:
print(np.zeros((2,3)))     # مصفوفة كلها أصفار
print(np.ones((3,3)))      # مصفوفة كلها واحدات
print(np.eye(3))           # مصفوفة هوية Identity Matrix
print(np.arange(0,10,2))   # مثل range() لكن لمصفوفة
print(np.linspace(0,1,5))  # أرقام متدرجة بين 0 و 1

🟢 العمليات الحسابية

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # جمع
print(a - b)   # طرح
print(a * b)   # ضرب عنصر بعنصر
print(a / b)   # قسمة

🟢 خصائص المصفوفة

In [2]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)   # أبعاد المصفوفة (صفوف × أعمدة)
print(arr.size)    # عدد العناصر
print(arr.ndim)    # عدد الأبعاد
print(arr.dtype)   # نوع البيانات

(2, 3)
6
2
int64

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]

In [4]:
arr = np.array([1, 2, 3, 4])

print(np.sum(arr))     # مجموع العناصر
print(np.mean(arr))    # المتوسط
print(np.std(arr))     # الانحراف المعياري
print(np.max(arr))     # أكبر قيمة
print(np.min(arr))     # أصغر قيمة

10
2.5
1.118033988749895
4
1

In [5]:
# درجات طلاب في مادة
grades = np.array([60, 70, 80, 90, 100])

print("المجموع:", np.sum(grades))
print("المتوسط:", np.mean(grades))
print("أعلى درجة:", np.max(grades))
print("أقل درجة:", np.min(grades))

المجموع: 400
المتوسط: 80.0
أعلى درجة: 100
أقل درجة: 60

In [7]:
import numpy as np1

In [13]:
arr1 = np1.array([1,2,6,3,4,8])
arr2 = np1.array( [[[1,2,3,5] ,[12,3,5,9]],[[1,2,3,5],[1,8,5,9] ] ])

arr2

array([[[ 1,  2,  3,  5],
        [12,  3,  5,  9]],

       [[ 1,  2,  3,  5],
        [ 1,  8,  5,  9]]])

In [18]:
print(np1.zeros((2,3)))
print(np1.ones((3,3)))
print(np1.eye(3))
print(np1.arange(0,10,2))
print(np1.linspace(0,1,5))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [20]:
print(np1.arange(0,10,2))

[0 2 4 6 8]

In [32]:
print(np1.arange(5,15,2))

[ 5  7  9 11 13]

In [39]:
print(arr2.shape)
print(arr2.size)
print(arr2.ndim)
print(arr2.dtype)
print(np1.sum(arr2))
print(np1.max(arr2))
print(np1.min(arr2))
print(np1.mean(arr2))
print(np1.std(arr2))

(2, 2, 4)
16
3
int64
74
12
1
4.625
3.2185982973959333

In [2]:
import pandas as pd
import numpy as np
data =[
     {'Name': 'Alice', 'Age': 25, 'Gender': 'Female', 'Email': 'alice@example.com', 'Address': '123 Main St', 'Salary': 60000},
    {'Name': 'Bob', 'Age': 30, 'Gender': 'Male', 'Email': 'bob@example.com', 'Address': '456 Oak Ave', 'Salary': 75000},
    {'Name': 'Charlie', 'Age': 28, 'Gender': 'Male', 'Email': 'charlie@example.com', 'Address': '789 Pine Ln', 'Salary': 80000},
    {'Name': 'David', 'Age': 35, 'Gender': 'Male', 'Email': 'david@example.com', 'Address': '1011 Elm Rd', 'Salary': 90000},
    {'Name': 'Eve', 'Age': 22, 'Gender': 'Female', 'Email': 'eve@example.com', 'Address': '1213 Birch Blvd', 'Salary': 55000}

]

df= pd.DataFrame(data)
df

      Name  Age  Gender                Email          Address  Salary
0    Alice   25  Female    alice@example.com      123 Main St   60000
1      Bob   30    Male      bob@example.com      456 Oak Ave   75000
2  Charlie   28    Male  charlie@example.com      789 Pine Ln   80000
3    David   35    Male    david@example.com      1011 Elm Rd   90000
4      Eve   22  Female      eve@example.com  1213 Birch Blvd   55000

In [46]:
df['salay_descond'] = df['Salary'] * 0.025
df

,Name,Age,Gender,Email,Address,Salary,salay_descond
0,Alice,25,Female,alice@example.com,123 Main St,60000,1500.0
1,Bob,30,Male,bob@example.com,456 Oak Ave,75000,1875.0
2,Charlie,28,Male,charlie@example.com,789 Pine Ln,80000,2000.0
3,David,35,Male,david@example.com,1011 Elm Rd,90000,2250.0
4,Eve,22,Female,eve@example.com,1213 Birch Blvd,55000,1375.0

In [50]:
df['username'] = df['Email'].str.split('@').str[0]
df
df

,Name,Age,Gender,Email,Address,Salary,salay_descond,username
0,Alice,25,Female,alice@example.com,123 Main St,60000,1500.0,alice
1,Bob,30,Male,bob@example.com,456 Oak Ave,75000,1875.0,bob
2,Charlie,28,Male,charlie@example.com,789 Pine Ln,80000,2000.0,charlie
3,David,35,Male,david@example.com,1011 Elm Rd,90000,2250.0,david
4,Eve,22,Female,eve@example.com,1213 Birch Blvd,55000,1375.0,eve

In [58]:
df ['name'] = df['Email'].str.split('@').str[0]
df

,Name,Age,Gender,Email,Address,Salary,salay_descond,username,name
0,Alice,25,Female,alice@example.com,123 Main St,60000,1500.0,alice,alice
1,Bob,30,Male,bob@example.com,456 Oak Ave,75000,1875.0,bob,bob
2,Charlie,28,Male,charlie@example.com,789 Pine Ln,80000,2000.0,charlie,charlie
3,David,35,Male,david@example.com,1011 Elm Rd,90000,2250.0,david,david
4,Eve,22,Female,eve@example.com,1213 Birch Blvd,55000,1375.0,eve,eve

In [64]:
df.loc[2:4 ,['Name','Salary','Email'] ]

      Name  Salary                Email
2  Charlie   80000  charlie@example.com
3    David   90000    david@example.com
4      Eve   55000      eve@example.com

In [67]:
df.iloc[2:4 ,2:7 ]

  Gender                Email      Address  Salary  salay_descond
2   Male  charlie@example.com  789 Pine Ln   80000         2000.0
3   Male    david@example.com  1011 Elm Rd   90000         2250.0

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           5 non-null      object
 1   Age            5 non-null      int64
 2   Gender         5 non-null      object
 3   Email          5 non-null      object
 4   Address        5 non-null      object
 5   Salary         5 non-null      int64
 6   salay_descond  5 non-null      float64
 7   username       5 non-null      object
 8   name           5 non-null      object
dtypes: float64(1), int64(2), object(6)
memory usage: 492.0+ bytes

In [75]:
df[['Age', 'Email' ] ]

   Age                Email
0   25    alice@example.com
1   30      bob@example.com
2   28  charlie@example.com
3   35    david@example.com
4   22      eve@example.com

In [76]:
df['Age']>30

0    False
1    False
2    False
3     True
4    False
Name: Age, dtype: bool

In [80]:
df[df['Salary'] >8000]

,Name,Age,Gender,Email,Address,Salary,salay_descond,username,name
0,Alice,25,Female,alice@example.com,123 Main St,60000,1500.0,alice,alice
1,Bob,30,Male,bob@example.com,456 Oak Ave,75000,1875.0,bob,bob
2,Charlie,28,Male,charlie@example.com,789 Pine Ln,80000,2000.0,charlie,charlie
3,David,35,Male,david@example.com,1011 Elm Rd,90000,2250.0,david,david
4,Eve,22,Female,eve@example.com,1213 Birch Blvd,55000,1375.0,eve,eve

In [84]:
df[df['Age']== 25]

,Name,Age,Gender,Email,Address,Salary,salay_descond,username,name
0,Alice,25,Female,alice@example.com,123 Main St,60000,1500.0,alice,alice

In [5]:
df[df['Salary']<=80000]

      Name  Age  Gender                Email          Address  Salary
0    Alice   25  Female    alice@example.com      123 Main St   60000
1      Bob   30    Male      bob@example.com      456 Oak Ave   75000
2  Charlie   28    Male  charlie@example.com      789 Pine Ln   80000
4      Eve   22  Female      eve@example.com  1213 Birch Blvd   55000

In [59]:
import pandas as pd
import numpy as np
data =[
     {'Name': 'Alice', 'Age': 25, 'Gender': 'Female', 'Email': 'alice@example.com', 'Address': '123 Main St', 'Salary': 60000},
    {'Name': 'Bob', 'Age': 30, 'Gender': 'Male', 'Email': 'bob@example.com', 'Address': '456 Oak Ave', 'Salary': 75000},
    {'Name': 'Charlie', 'Age': 28, 'Gender': 'Male', 'Email': 'charlie@example.com', 'Address': '789 Pine Ln', 'Salary': 80000},
    {'Name': 'David', 'Age': 35, 'Gender': 'Male', 'Email': 'david@example.com', 'Address': '1011 Elm Rd', 'Salary': 90000},
    {'Name': 'Eve', 'Age': 22, 'Gender': 'Female', 'Email': 'eve@example.com', 'Address': '1213 Birch Blvd', 'Salary': 55000}

]

df= pd.DataFrame(data)
df

      Name  Age  Gender                Email          Address  Salary
0    Alice   25  Female    alice@example.com      123 Main St   60000
1      Bob   30    Male      bob@example.com      456 Oak Ave   75000
2  Charlie   28    Male  charlie@example.com      789 Pine Ln   80000
3    David   35    Male    david@example.com      1011 Elm Rd   90000
4      Eve   22  Female      eve@example.com  1213 Birch Blvd   55000

In [17]:
df [ (df['Gender'] == 'Male') & (df['Salary'] >5000)  ]

      Name  Age Gender                Email      Address  Salary
1      Bob   30   Male      bob@example.com  456 Oak Ave   75000
2  Charlie   28   Male  charlie@example.com  789 Pine Ln   80000
3    David   35   Male    david@example.com  1011 Elm Rd   90000

In [18]:
df [ (df['Gender'] == 'Male') & (df['Salary'] >5000) ]

      Name  Age Gender                Email      Address  Salary
1      Bob   30   Male      bob@example.com  456 Oak Ave   75000
2  Charlie   28   Male  charlie@example.com  789 Pine Ln   80000
3    David   35   Male    david@example.com  1011 Elm Rd   90000

In [26]:
df [(df['Name'] == 'Alice' ) & (df['Salary'] ==60000
 ) ]

    Name  Age  Gender              Email      Address  Salary
0  Alice   25  Female  alice@example.com  123 Main St   60000

In [27]:
df[df['Age'].isin([35 , 30 , 25]) ]

    Name  Age  Gender              Email      Address  Salary
0  Alice   25  Female  alice@example.com  123 Main St   60000
1    Bob   30    Male    bob@example.com  456 Oak Ave   75000
3  David   35    Male  david@example.com  1011 Elm Rd   90000

In [30]:
df[df['Salary'].between(75000 , 80000)]

      Name  Age Gender                Email      Address  Salary
1      Bob   30   Male      bob@example.com  456 Oak Ave   75000
2  Charlie   28   Male  charlie@example.com  789 Pine Ln   80000

In [32]:
df[(df ['Age']> 25 ) & (df ['Salary'] > 20000 ) ]

      Name  Age Gender                Email      Address  Salary
1      Bob   30   Male      bob@example.com  456 Oak Ave   75000
2  Charlie   28   Male  charlie@example.com  789 Pine Ln   80000
3    David   35   Male    david@example.com  1011 Elm Rd   90000

In [34]:
df[(df['Age']== 25) | (df['Salary'] > 20000 ) ]

      Name  Age  Gender                Email          Address  Salary
0    Alice   25  Female    alice@example.com      123 Main St   60000
1      Bob   30    Male      bob@example.com      456 Oak Ave   75000
2  Charlie   28    Male  charlie@example.com      789 Pine Ln   80000
3    David   35    Male    david@example.com      1011 Elm Rd   90000
4      Eve   22  Female      eve@example.com  1213 Birch Blvd   55000

In [35]:
df[(df['Age']== 25) | (df['Salary']>70000 ) & (df['Email']) ]

      Name  Age  Gender                Email      Address  Salary
0    Alice   25  Female    alice@example.com  123 Main St   60000
1      Bob   30    Male      bob@example.com  456 Oak Ave   75000
2  Charlie   28    Male  charlie@example.com  789 Pine Ln   80000
3    David   35    Male    david@example.com  1011 Elm Rd   90000

In [38]:
df[df['Age'].isin ([25 , 30])]

    Name  Age  Gender              Email      Address  Salary
0  Alice   25  Female  alice@example.com  123 Main St   60000
1    Bob   30    Male    bob@example.com  456 Oak Ave   75000

In [39]:
df[df['Salary'].between(75000 , 80000)]

      Name  Age Gender                Email      Address  Salary
1      Bob   30   Male      bob@example.com  456 Oak Ave   75000
2  Charlie   28   Male  charlie@example.com  789 Pine Ln   80000

In [41]:
df[df['Age'].isin([10 , 30])]

  Name  Age Gender            Email      Address  Salary
1  Bob   30   Male  bob@example.com  456 Oak Ave   75000

In [42]:
# prompt: create me a data frame with data types columns for integrets and column for string and one for boolean and floats and dates

import pandas as pd
import numpy as np

# Create a dictionary with different data types
data = {
    'IntegerColumn': [1, 2, 3, 4, 5],
    'StringColumn': ['A', 'B', 'C', 'D', 'E'],
    'BooleanColumn': [True, False, True, False, True],
    'FloatColumn': [1.1, 2.2, 3.3, 4.4, 5.5],
    'DateColumn': pd.to_datetime(['2023-10-26', '2023-10-27', '2023-10-28', '2023-10-29', '2023-10-30'])
}

# Create a Pandas DataFrame from the dictionary
df3 = pd.DataFrame(data)

# Print the DataFrame
df3

   IntegerColumn StringColumn  BooleanColumn  FloatColumn DateColumn
0              1            A           True          1.1 2023-10-26
1              2            B          False          2.2 2023-10-27
2              3            C           True          3.3 2023-10-28
3              4            D          False          4.4 2023-10-29
4              5            E           True          5.5 2023-10-30

In [43]:
df

      Name  Age  Gender                Email          Address  Salary
0    Alice   25  Female    alice@example.com      123 Main St   60000
1      Bob   30    Male      bob@example.com      456 Oak Ave   75000
2  Charlie   28    Male  charlie@example.com      789 Pine Ln   80000
3    David   35    Male    david@example.com      1011 Elm Rd   90000
4      Eve   22  Female      eve@example.com  1213 Birch Blvd   55000

In [44]:
df3

   IntegerColumn StringColumn  BooleanColumn  FloatColumn DateColumn
0              1            A           True          1.1 2023-10-26
1              2            B          False          2.2 2023-10-27
2              3            C           True          3.3 2023-10-28
3              4            D          False          4.4 2023-10-29
4              5            E           True          5.5 2023-10-30

In [45]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   IntegerColumn  5 non-null      int64
 1   StringColumn   5 non-null      object
 2   BooleanColumn  5 non-null      bool
 3   FloatColumn    5 non-null      float64
 4   DateColumn     5 non-null      datetime64[ns]
dtypes: bool(1), datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 297.0+ bytes

In [48]:
df['Salary'] =df['Salary'].astype('float')
df

      Name  Age  Gender                Email          Address   Salary
0    Alice   25  Female    alice@example.com      123 Main St  60000.0
1      Bob   30    Male      bob@example.com      456 Oak Ave  75000.0
2  Charlie   28    Male  charlie@example.com      789 Pine Ln  80000.0
3    David   35    Male    david@example.com      1011 Elm Rd  90000.0
4      Eve   22  Female      eve@example.com  1213 Birch Blvd  55000.0

In [51]:
df.select_dtypes('number')

   Age   Salary
0   25  60000.0
1   30  75000.0
2   28  80000.0
3   35  90000.0
4   22  55000.0

In [64]:
df.select_dtypes('object')

         Gender                Email          Address
Name
Alice    Female    alice@example.com      123 Main St
Bob        Male      bob@example.com      456 Oak Ave
Charlie    Male  charlie@example.com      789 Pine Ln
David      Male    david@example.com      1011 Elm Rd
Eve      Female      eve@example.com  1213 Birch Blvd

In [66]:

import pandas as pd
import numpy as np
data =[
     {'Name': 'Alice', 'Age': 25, 'Gender': 'Female', 'Email': 'alice@example.com', 'Address': '123 Main St', 'Salary': 60000},
    {'Name': 'Bob', 'Age': 30, 'Gender': 'Male', 'Email': 'bob@example.com', 'Address': '456 Oak Ave', 'Salary': 75000},
    {'Name': 'Charlie', 'Age': 28, 'Gender': 'Male', 'Email': 'charlie@example.com', 'Address': '789 Pine Ln', 'Salary': 80000},
    {'Name': 'David', 'Age': 35, 'Gender': 'Male', 'Email': 'david@example.com', 'Address': '1011 Elm Rd', 'Salary': 90000},
    {'Name': 'Eve', 'Age': 22, 'Gender': 'Female', 'Email': 'eve@example.com', 'Address': '1213 Birch Blvd', 'Salary': 55000}

]

df= pd.DataFrame(data)
df

      Name  Age  Gender                Email          Address  Salary
0    Alice   25  Female    alice@example.com      123 Main St   60000
1      Bob   30    Male      bob@example.com      456 Oak Ave   75000
2  Charlie   28    Male  charlie@example.com      789 Pine Ln   80000
3    David   35    Male    david@example.com      1011 Elm Rd   90000
4      Eve   22  Female      eve@example.com  1213 Birch Blvd   55000

In [76]:
 df.set_index('Name' , inplace = True)

KeyError: "None of ['Name'] are in the columns"

In [74]:
df.reset_index()

      Name  Age  Gender                Email          Address  Salary
0    Alice   25  Female    alice@example.com      123 Main St   60000
1      Bob   30    Male      bob@example.com      456 Oak Ave   75000
2  Charlie   28    Male  charlie@example.com      789 Pine Ln   80000
3    David   35    Male    david@example.com      1011 Elm Rd   90000
4      Eve   22  Female      eve@example.com  1213 Birch Blvd   55000

In [78]:
df.to_csv('Python script.csv')
df

         Age  Gender                Email          Address  Salary
Name
Alice     25  Female    alice@example.com      123 Main St   60000
Bob       30    Male      bob@example.com      456 Oak Ave   75000
Charlie   28    Male  charlie@example.com      789 Pine Ln   80000
David     35    Male    david@example.com      1011 Elm Rd   90000
Eve       22  Female      eve@example.com  1213 Birch Blvd   55000

In [80]:
#

In [82]:
from google.colab import files
files.download("myfile.pdf")

FileNotFoundError: Cannot find file: myfile.pdf